<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0 (Python 3.11.5 on darwin)" generated="2024-07-02T10:45:33.155431" rpa="false" schemaversion="5">
<suite id="s1" name="Picpay" source="/Users/Automacao_Home/tests/Picpay.robot">
<test id="s1-t1" name="Exibição dos itens" line="29">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.261169" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1068a2310&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.263090" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106f2a3d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.265223" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104b44d10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.267174" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.267044" elapsed="0.006737">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.274598" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.274694" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104b44c50&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.253207" elapsed="0.022400">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104b44c50&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.253100" elapsed="0.022551">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104b44c50&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.275754" elapsed="0.000012"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.252852" elapsed="0.022973">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104b44c50&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.276245" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.276185" elapsed="0.000215">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.277059" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.277119" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.276086" elapsed="0.001135">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.277274" elapsed="0.000676"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.275967" elapsed="0.002024">No application is open</status>
</kw>
<tag>dia_a_dia</tag>
<status status="FAIL" start="2024-07-02T10:45:33.252619" elapsed="0.025404">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104b44c50&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t2" name=" Item com tag" line="35">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.280917" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790dd90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.282645" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790eb10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.284040" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791c5d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.285799" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.285644" elapsed="0.001234">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.287836" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.287925" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791d310&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.278573" elapsed="0.010280">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791d310&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.278470" elapsed="0.010416">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791d310&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.288971" elapsed="0.000009"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.278239" elapsed="0.010790">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791d310&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.289413" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.289362" elapsed="0.000205">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.290350" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.290412" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.289277" elapsed="0.001243">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.290577" elapsed="0.001248"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.289164" elapsed="0.002716">No application is open</status>
</kw>
<tag>dia_a_dia</tag>
<status status="FAIL" start="2024-07-02T10:45:33.278109" elapsed="0.013826">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791d310&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t3" name="Exibição dos itens no carrossel" line="41">
<tag>robot:skip</tag>
<status status="SKIP" start="2024-07-02T10:45:33.292060" elapsed="0.000185">Test skipped using 'robot:skip' tag.</status>
</test>
<test id="s1-t4" name="Validar menu pix" line="47">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.295337" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790e590&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.297309" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790db50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.301239" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790d710&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.308231" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.307475" elapsed="0.005323">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.315180" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.317205" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe6dd0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.292703" elapsed="0.027182">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe6dd0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.292592" elapsed="0.027400">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe6dd0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.320089" elapsed="0.000010"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.292469" elapsed="0.027684">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe6dd0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.320589" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.320524" elapsed="0.000229">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.321505" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.321569" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.320428" elapsed="0.001304">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.321802" elapsed="0.002567"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.320317" elapsed="0.004304">No application is open</status>
</kw>
<tag>dia_a_dia</tag>
<status status="FAIL" start="2024-07-02T10:45:33.292321" elapsed="0.032391">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe6dd0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t5" name="Validar menu pagar boletos" line="53">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.328618" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790c7d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.330748" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791d350&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.332228" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791d150&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.333683" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.333585" elapsed="0.001154">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.335525" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.335599" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107929d10&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.325901" elapsed="0.010555">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107929d10&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.325658" elapsed="0.010826">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107929d10&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.336560" elapsed="0.000008"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.325386" elapsed="0.011227">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107929d10&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.337020" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.336975" elapsed="0.000198">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.337883" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.337943" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.336902" elapsed="0.001145">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.338099" elapsed="0.000861"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.336796" elapsed="0.002206">No application is open</status>
</kw>
<tag>dia_a_dia</tag>
<status status="FAIL" start="2024-07-02T10:45:33.324931" elapsed="0.014106">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107929d10&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t6" name="Validar menu pagar pessoas" line="59">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.341671" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790ec10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.343190" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790ff10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.344723" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790df90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.346252" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.346143" elapsed="0.001190">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.348166" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.348248" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe76d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.339458" elapsed="0.009731">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe76d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.339359" elapsed="0.009858">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe76d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.349295" elapsed="0.000008"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.339276" elapsed="0.010069">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe76d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.349671" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.349628" elapsed="0.000179">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.350433" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.350487" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.349561" elapsed="0.001028">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.350634" elapsed="0.000805"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.349469" elapsed="0.002004">No application is open</status>
</kw>
<tag>dia_a_dia</tag>
<status status="FAIL" start="2024-07-02T10:45:33.339133" elapsed="0.012367">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe76d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t7" name="Validar menu QRCode" line="65">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.354333" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792c990&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.356214" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe7910&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.357918" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790fd10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.359773" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.359684" elapsed="0.001066">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.361452" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.361508" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790dd90&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.351929" elapsed="0.010448">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790dd90&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.351840" elapsed="0.010568">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790dd90&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.362474" elapsed="0.000006"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.351764" elapsed="0.010760">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790dd90&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.362858" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.362812" elapsed="0.000201">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.363675" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.363731" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.362734" elapsed="0.001093">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.363875" elapsed="0.001079"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.362646" elapsed="0.002366">No application is open</status>
</kw>
<tag>dia_a_dia</tag>
<status status="FAIL" start="2024-07-02T10:45:33.351634" elapsed="0.013422">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790dd90&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t8" name="Validar menu Recarga de celular" line="71">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.367495" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791d390&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.369990" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790cad0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.371737" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790fd10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.373625" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.373483" elapsed="0.001182">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.375391" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.375452" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe6790&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.365562" elapsed="0.010688">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe6790&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.365437" elapsed="0.010838">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe6790&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.376335" elapsed="0.000006"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.365330" elapsed="0.011050">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe6790&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.376695" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.376652" elapsed="0.000185">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.377460" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.377513" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.376591" elapsed="0.001023">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.377656" elapsed="0.000774"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.376506" elapsed="0.001956">No application is open</status>
</kw>
<tag>dia_a_dia</tag>
<status status="FAIL" start="2024-07-02T10:45:33.365166" elapsed="0.013329">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe6790&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t9" name="Validar menu cofrinho" line="77">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.381204" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106f0aed0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.382838" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107933810&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.384476" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107931010&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.386496" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.386416" elapsed="0.001048">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.388154" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.388216" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792c950&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.378879" elapsed="0.010298">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792c950&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.378782" elapsed="0.010493">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792c950&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.389351" elapsed="0.000008"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.378707" elapsed="0.010701">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792c950&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.389844" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.389771" elapsed="0.000256">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.390796" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.390858" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.389686" elapsed="0.001277">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.391010" elapsed="0.000823"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.389570" elapsed="0.002301">No application is open</status>
</kw>
<tag>dia_a_dia</tag>
<status status="FAIL" start="2024-07-02T10:45:33.378587" elapsed="0.013318">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792c950&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t10" name="Validar menu pagar fatura" line="83">
<tag>robot:skip</tag>
<status status="SKIP" start="2024-07-02T10:45:33.391996" elapsed="0.000095">Test skipped using 'robot:skip' tag.</status>
</test>
<test id="s1-t11" name="Validar menu cartao de transporte" line="89">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.395006" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106bcc310&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.396748" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107932890&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.398442" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792ae10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.400045" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.399926" elapsed="0.001039">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.401631" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.401683" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791e550&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.392435" elapsed="0.010017">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791e550&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.392354" elapsed="0.010123">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791e550&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.402537" elapsed="0.000006"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.392276" elapsed="0.010344">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791e550&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.402916" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.402875" elapsed="0.000180">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.403707" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.403760" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.402813" elapsed="0.001055">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.403920" elapsed="0.000839"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.402731" elapsed="0.002066">No application is open</status>
</kw>
<tag>dia_a_dia</tag>
<status status="FAIL" start="2024-07-02T10:45:33.392154" elapsed="0.012672">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791e550&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t12" name="Validar menu Gift Cards" line="95">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.407212" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792df90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.408705" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790f5d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.409829" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794d090&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.411684" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.411504" elapsed="0.001248">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.413474" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.413537" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794dd90&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.405216" elapsed="0.009128">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794dd90&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.405128" elapsed="0.009244">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794dd90&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.414450" elapsed="0.000008"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.405045" elapsed="0.009466">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794dd90&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.414842" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.414795" elapsed="0.000195">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.415660" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.415716" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.414724" elapsed="0.001093">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.415861" elapsed="0.000803"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.414628" elapsed="0.002068">No application is open</status>
</kw>
<tag>dia_a_dia</tag>
<status status="FAIL" start="2024-07-02T10:45:33.404916" elapsed="0.011810">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794dd90&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t13" name="Validar menu footer" line="101">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.419578" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795fa90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.421436" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794c790&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.422753" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790c350&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.424274" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.424164" elapsed="0.001038">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.425965" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.426027" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792e610&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.417128" elapsed="0.009752">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792e610&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.417044" elapsed="0.009869">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792e610&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.426985" elapsed="0.000008"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.416969" elapsed="0.010071">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792e610&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.427429" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.427373" elapsed="0.000245">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.428432" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.428512" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.427295" elapsed="0.001369">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.428739" elapsed="0.001369"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.427178" elapsed="0.002973">No application is open</status>
</kw>
<tag>footer</tag>
<status status="FAIL" start="2024-07-02T10:45:33.416843" elapsed="0.013348">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792e610&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t14" name="Acessar Pix pelo gavetao" line="107">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.432841" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795ed90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.434585" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795fc90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.436121" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795e690&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.438016" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.437941" elapsed="0.000994">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.439574" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.439624" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795f550&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.430596" elapsed="0.009924">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795f550&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.430499" elapsed="0.010061">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795f550&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.440640" elapsed="0.000007"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.430418" elapsed="0.010276">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795f550&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.441044" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.440995" elapsed="0.000210">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.441862" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.441912" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.440917" elapsed="0.001100">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.442070" elapsed="0.000821"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.440820" elapsed="0.002112">No application is open</status>
</kw>
<tag>gavetao</tag>
<status status="FAIL" start="2024-07-02T10:45:33.430281" elapsed="0.012692">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795f550&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t15" name="Acessar menu pagar Boletos pelo gavetao" line="114">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.451652" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107970f90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.453581" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107972990&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.455398" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107970e90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.457505" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.457382" elapsed="0.001393">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.459527" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.459600" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795c310&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.448973" elapsed="0.011446">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795c310&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.448867" elapsed="0.011617">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795c310&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.460558" elapsed="0.000008"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.448746" elapsed="0.011864">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795c310&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.461024" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.460978" elapsed="0.000189">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.461831" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.461886" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.460905" elapsed="0.001084">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.462033" elapsed="0.000652"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.460729" elapsed="0.001987">No application is open</status>
</kw>
<tag>gavetao</tag>
<status status="FAIL" start="2024-07-02T10:45:33.443075" elapsed="0.019668">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795c310&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t16" name="Acessar o menu pagar com QR Code pelo gavetao" line="121">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.465663" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795c110&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.467526" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795e810&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.469332" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795e990&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.470765" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.470693" elapsed="0.000977">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.472401" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.472455" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107933d10&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.463108" elapsed="0.010180">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107933d10&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.463030" elapsed="0.010285">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107933d10&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.473386" elapsed="0.000007"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.462957" elapsed="0.010475">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107933d10&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.473882" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.473838" elapsed="0.000181">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.474692" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.474746" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.473665" elapsed="0.001181">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.474892" elapsed="0.000708"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.473573" elapsed="0.002060">No application is open</status>
</kw>
<tag>gavetao</tag>
<status status="FAIL" start="2024-07-02T10:45:33.462828" elapsed="0.012832">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107933d10&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t17" name="Acessar o menu pagar pessoas pelo gavetao" line="128">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.478454" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107970090&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.480451" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107930450&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.482799" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1079331d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.484523" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.484439" elapsed="0.001250">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.486453" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.486529" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1079314d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.476043" elapsed="0.011268">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1079314d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.475960" elapsed="0.011378">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1079314d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.487414" elapsed="0.000008"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.475881" elapsed="0.011583">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1079314d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.487891" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.487734" elapsed="0.000299">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.488676" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.488727" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.487668" elapsed="0.001156">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.488866" elapsed="0.000669"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.487580" elapsed="0.001986">No application is open</status>
</kw>
<tag>gavetao</tag>
<status status="FAIL" start="2024-07-02T10:45:33.475749" elapsed="0.013844">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1079314d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t18" name="Acessar o menu cobrar alguem pelo gavetao" line="135">
<kw name="Start session" owner="base" type="SETUP">
<kw name="Run Keyword If" owner="BuiltIn">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.492164" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794e790&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.494010" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794d410&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.496406" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795ce50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.498109" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.498028" elapsed="0.001054">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.499818" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.499884" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1051fb950&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-02T10:45:33.489983" elapsed="0.010830">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1051fb950&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<arg>'${PLATFORM}' == 'IOS'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=XCUItest</arg>
<arg>platformName=IOS</arg>
<arg>DeviceName=iPhone</arg>
<arg>platformVersion=16.7.7</arg>
<arg>bundleId=com.picpay.PicPay</arg>
<arg>udid=4a18fdb2b0e6a3e07adc857f54f1ca6e1b09810e</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.489901" elapsed="0.010944">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1051fb950&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Run Keyword If" owner="BuiltIn">
<arg>'${PLATFORM}' == 'Android'</arg>
<arg>Open Application</arg>
<arg>http://localhost:4723</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>DeviceName=SM-G570M</arg>
<arg>platformVersion=8.0.0</arg>
<arg>bundleId=com.picpay.PicPay-Development</arg>
<arg>udid=42006644d49f646b</arg>
<arg>autoAcceptAlerts=true</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="NOT RUN" start="2024-07-02T10:45:33.500928" elapsed="0.000008"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.489829" elapsed="0.011160">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1051fb950&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<kw name="Finish session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-02T10:45:33.501377" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.501319" elapsed="0.000392">No application is open</status>
</kw>
<msg time="2024-07-02T10:45:33.502410" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.502465" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-02T10:45:33.501233" elapsed="0.001336">No application is open</status>
</kw>
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-07-02T10:45:33.502613" elapsed="0.000665"/>
</kw>
<status status="FAIL" start="2024-07-02T10:45:33.501118" elapsed="0.002193">No application is open</status>
</kw>
<tag>gavetao</tag>
<status status="FAIL" start="2024-07-02T10:45:33.489703" elapsed="0.013636">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1051fb950&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<doc>classe criada para a realização dos testes</doc>
<status status="FAIL" start="2024-07-02T10:45:33.156646" elapsed="0.346832"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="16" skip="2">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="10" skip="0">dia_a_dia</stat>
<stat pass="0" fail="1" skip="0">footer</stat>
<stat pass="0" fail="5" skip="0">gavetao</stat>
</tag>
<suite>
<stat pass="0" fail="16" skip="2" id="s1" name="Picpay">Picpay</stat>
</suite>
</statistics>
<errors>
<msg time="2024-07-02T10:45:33.261169" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1068a2310&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.263090" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106f2a3d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.265223" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104b44d10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.274598" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.277059" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.280917" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790dd90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.282645" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790eb10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.284040" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791c5d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.287836" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.290350" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.295337" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790e590&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.297309" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790db50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.301239" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790d710&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.315180" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.321505" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.328618" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790c7d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.330748" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791d350&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.332228" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791d150&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.335525" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.337883" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.341671" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790ec10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.343190" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790ff10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.344723" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790df90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.348166" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.350433" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.354333" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792c990&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.356214" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106fe7910&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.357918" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790fd10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.361452" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.363675" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.367495" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10791d390&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.369990" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790cad0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.371737" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790fd10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.375391" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.377460" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.381204" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106f0aed0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.382838" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107933810&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.384476" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107931010&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.388154" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.390796" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.395006" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106bcc310&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.396748" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107932890&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.398442" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792ae10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.401631" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.403707" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.407212" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10792df90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.408705" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790f5d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.409829" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794d090&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.413474" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.415660" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.419578" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795fa90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.421436" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794c790&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.422753" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10790c350&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.425965" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.428432" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.432841" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795ed90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.434585" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795fc90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.436121" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795e690&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.439574" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.441862" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.451652" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107970f90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.453581" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107972990&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.455398" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107970e90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.459527" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.461831" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.465663" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795c110&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.467526" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795e810&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.469332" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795e990&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.472401" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.474692" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.478454" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107970090&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.480451" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x107930450&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.482799" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1079331d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.486453" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.488676" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.492164" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794e790&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.494010" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10794d410&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.496406" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10795ce50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session</msg>
<msg time="2024-07-02T10:45:33.499818" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-02T10:45:33.502410" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
